import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export interface ReportData {
  goal: string;
  goalLabel: string;
  goalLabelEn: string;
  age: number;
  budget: number;
  ielts: number;
  educationLabel?: string;
  educationLabelEn?: string;
  workYearsLabel?: string;
  workYearsLabelEn?: string;
  hasFrench?: boolean;
  hasJobOffer?: boolean;
  hasCanadaExperience?: boolean;
  intendedStudyLevel?: string;
  intendedStudyLevelEn?: string;
  hasCanadaStudyBefore?: boolean;
  visitPurpose?: string;
  visitPurposeEn?: string;
  hasStableIncome?: boolean;
  previousCanadaVisit?: boolean;
  hasCanadaWorkBefore?: boolean;
  riskScore: number;
  statusLabel: string;
  statusLabelEn: string;
  radar: { label: string; labelEn: string; value: number }[];
  recommendations: { zh: string; en: string }[];
}

const DISCLAIMER_ZH =
  "本报告由加移(Jiayi)平台工具自动生成，仅供信息参考与自我评估，不构成任何法律、移民或专业建议。移民与签证结果取决于个案及移民局裁量，平台不对使用本报告产生的任何决定或后果负责。如需正式建议，请咨询持牌移民顾问(RCIC)或律师。";
const DISCLAIMER_EN =
  "This report is auto-generated by Jiayi platform tools for informational and self-assessment purposes only and does not constitute legal, immigration, or professional advice. Immigration and visa outcomes depend on individual cases and officer discretion. The platform is not responsible for any decisions or outcomes arising from the use of this report. For formal advice, please consult a licensed immigration consultant (RCIC) or lawyer.";

const A4_W_PX = 794;
const A4_H_PX = 1123;

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildReportHtml(data: ReportData): string {
  const dateStr = new Date().toLocaleString("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });

  const radarRows = data.radar
    .map(
      (r) =>
        `<tr><td class="dim-name">${esc(r.label)}</td><td class="dim-name-en">${esc(r.labelEn)}</td><td class="dim-val">${Math.round(r.value)}</td></tr>`
    )
    .join("");

  const recItems = data.recommendations
    .map(
      (rec) =>
        `<li class="rec-item"><span class="rec-zh">${esc(rec.zh)}</span><span class="rec-en">${esc(rec.en)}</span></li>`
    )
    .join("");

  return `
<div class="report" style="
  font-family: 'Microsoft YaHei', 'PingFang SC', 'SimHei', 'SimSun', sans-serif;
  width: ${A4_W_PX}px;
  min-height: ${A4_H_PX}px;
  padding: 48px 56px;
  box-sizing: border-box;
  background: #fff;
  color: #1a1a1a;
  font-size: 14px;
  line-height: 1.5;
">
  <div class="report-head" style="border-bottom: 3px solid #0d9488; padding-bottom: 16px; margin-bottom: 28px;">
    <h1 style="margin: 0; font-size: 24px; font-weight: 700; color: #0f172a;">
      风险指南针报告 Risk Compass Report
    </h1>
    <p style="margin: 8px 0 0; font-size: 12px; color: #64748b;">
      生成时间 Generated: ${dateStr}
    </p>
  </div>

  <section class="section" style="margin-bottom: 24px;">
    <h2 class="section-title">1. 输入摘要 Input Summary</h2>
    <table class="data-table" style="width: 100%; border-collapse: collapse; font-size: 13px;">
      <tr><td class="label">目标 Goal</td><td class="value">${esc(data.goalLabel)} (${esc(data.goalLabelEn)})</td></tr>
      <tr><td class="label">年龄 Age</td><td class="value">${data.age}</td></tr>
      <tr><td class="label">预算(万加元) Budget (CAD 10k)</td><td class="value">${data.budget}</td></tr>
      <tr><td class="label">IELTS 总分 Overall</td><td class="value">${data.ielts}</td></tr>
      ${data.educationLabel != null ? `<tr><td class="label">学历 Education</td><td class="value">${esc(data.educationLabel)} (${esc(data.educationLabelEn || "")})</td></tr>` : ""}
      ${data.workYearsLabel != null ? `<tr><td class="label">工作经验 Work Exp.</td><td class="value">${esc(data.workYearsLabel)} (${esc(data.workYearsLabelEn || "")})</td></tr>` : ""}
      ${data.hasFrench != null ? `<tr><td class="label">法语 French</td><td class="value">${data.hasFrench ? "有 Yes" : "无 No"}</td></tr>` : ""}
      ${data.hasJobOffer != null ? `<tr><td class="label">雇主 offer Job Offer</td><td class="value">${data.hasJobOffer ? "有 Yes" : "无 No"}</td></tr>` : ""}
      ${data.hasCanadaExperience != null ? `<tr><td class="label">加拿大经历 Canada Exp.</td><td class="value">${data.hasCanadaExperience ? "有 Yes" : "无 No"}</td></tr>` : ""}
      ${data.intendedStudyLevel != null ? `<tr><td class="label">计划就读层次 Intended Level</td><td class="value">${esc(data.intendedStudyLevel)} ${data.intendedStudyLevelEn ? `(${esc(data.intendedStudyLevelEn)})` : ""}</td></tr>` : ""}
      ${data.hasCanadaStudyBefore != null ? `<tr><td class="label">加拿大学习经历 Canada Study Before</td><td class="value">${data.hasCanadaStudyBefore ? "有 Yes" : "无 No"}</td></tr>` : ""}
      ${data.visitPurpose != null ? `<tr><td class="label">访问目的 Visit Purpose</td><td class="value">${esc(data.visitPurpose)} ${data.visitPurposeEn ? `(${esc(data.visitPurposeEn)})` : ""}</td></tr>` : ""}
      ${data.hasStableIncome != null ? `<tr><td class="label">稳定收入 Stable Income</td><td class="value">${data.hasStableIncome ? "有 Yes" : "无 No"}</td></tr>` : ""}
      ${data.previousCanadaVisit != null ? `<tr><td class="label">曾访加 Previous Visit</td><td class="value">${data.previousCanadaVisit ? "有 Yes" : "无 No"}</td></tr>` : ""}
      ${data.hasCanadaWorkBefore != null ? `<tr><td class="label">加拿大工作经历 Canada Work Before</td><td class="value">${data.hasCanadaWorkBefore ? "有 Yes" : "无 No"}</td></tr>` : ""}
    </table>
  </section>

  <section class="section" style="margin-bottom: 24px;">
    <h2 class="section-title">2. 风险概览 Risk Overview</h2>
    <div style="display: flex; gap: 24px; align-items: center; flex-wrap: wrap;">
      <div class="score-box" style="
        background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%);
        border: 1px solid #86efac;
        border-radius: 12px;
        padding: 16px 24px;
        min-width: 120px;
      ">
        <div style="font-size: 11px; color: #166534; margin-bottom: 4px;">综合风险指数 Overall Risk</div>
        <div style="font-size: 28px; font-weight: 700; color: #15803d;">${data.riskScore}%</div>
      </div>
      <div style="
        padding: 10px 16px;
        border-radius: 8px;
        background: #f1f5f9;
        font-weight: 600;
        color: #0f172a;
      ">${esc(data.statusLabel)} / ${esc(data.statusLabelEn)}</div>
    </div>
  </section>

  <section class="section" style="margin-bottom: 24px;">
    <h2 class="section-title">3. 五维评估 Five Dimensions</h2>
    <table class="dim-table" style="width: 100%; border-collapse: collapse; font-size: 13px;">
      <thead>
        <tr style="background: #f8fafc; border-bottom: 2px solid #e2e8f0;">
          <th style="text-align: left; padding: 10px 12px;">维度 Dimension</th>
          <th style="text-align: left; padding: 10px 12px;">English</th>
          <th style="text-align: right; padding: 10px 12px;">数值 Value</th>
        </tr>
      </thead>
      <tbody>
        ${radarRows}
      </tbody>
    </table>
  </section>

  <section class="section" style="margin-bottom: 24px;">
    <h2 class="section-title">4. 系统建议 Recommendations</h2>
    <ul class="rec-list" style="margin: 0; padding-left: 20px;">
      ${recItems}
    </ul>
  </section>

  <section class="section" style="margin-bottom: 24px;">
    <h2 class="section-title">5. 评估依据与数据来源 Assessment Basis & Data Sources</h2>
    <p style="margin: 0 0 8px; font-size: 12px; color: #334155;"><strong>综合风险指数：</strong>根据目标、年龄、预算、IELTS、学历、工作年限、法语、雇主 offer、加拿大经历等参数，参照 IRCC 及常见项目一般性要求加权计算。本模型参考平台 AI 顾问知识库与公开项目信息，非 IRCC 官方算法。</p>
    <p style="margin: 0 0 8px; font-size: 11px; color: #64748b;">Overall risk: weighted by goal, age, budget, IELTS, education, work experience, French, job offer, Canada experience; references IRCC-style criteria and platform knowledge base.</p>
    <p style="margin: 0 0 4px; font-size: 12px; color: #334155;"><strong>五维：</strong>财务(预算/学历)、语言(IELTS/法语)、政策(路径)、雇主(offer/工签)、背景(年龄/学历/工作年限/加拿大经历)。</p>
    <p style="margin: 0 0 8px; font-size: 12px; color: #334155;"><strong>数据来源：</strong>参数与权重参照 IRCC 及各省官网常见项目条件与加移 AI 顾问知识库整理，非官方打分或审批算法。具体以 IRCC 及各省官网为准。</p>
    <p style="margin: 0; font-size: 11px; color: #64748b;">Parameters reference IRCC/provincial criteria and Jiayi AI knowledge base. Refer to IRCC and provincial sites for official requirements.</p>
  </section>

  <div class="disclaimer" style="
    margin-top: 28px;
    padding: 20px;
    background: #fffbeb;
    border: 1px solid #fcd34d;
    border-radius: 8px;
    font-size: 12px;
  ">
    <div style="font-weight: 700; color: #92400e; margin-bottom: 8px;">法律与风险提示 Legal & Risk Disclaimer</div>
    <p style="margin: 0 0 8px; color: #1e293b;">${esc(DISCLAIMER_ZH)}</p>
    <p style="margin: 0; color: #475569; font-size: 11px;">${esc(DISCLAIMER_EN)}</p>
  </div>

  <div style="margin-top: 24px; font-size: 11px; color: #94a3b8; text-align: center;">
    Jiayi · jiayi.co · 本平台不提供移民或法律服务 No immigration or legal services provided.
  </div>
</div>
<style>
  .report .section-title { font-size: 15px; font-weight: 700; color: #0d9488; margin: 0 0 12px; }
  .report .data-table .label { width: 42%; padding: 8px 12px; color: #64748b; border-bottom: 1px solid #e2e8f0; }
  .report .data-table .value { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  .report .dim-table td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  .report .dim-name { font-weight: 500; } .report .dim-name-en { color: #64748b; font-size: 12px; }
  .report .dim-val { text-align: right; font-weight: 600; color: #0d9488; }
  .report .rec-item { margin-bottom: 12px; } .report .rec-zh { display: block; margin-bottom: 2px; }
  .report .rec-en { display: block; color: #64748b; font-size: 12px; }
</style>
`;
}

export function downloadReportPdf(data: ReportData): void {
  if (typeof document === "undefined") return;

  const wrapper = document.createElement("div");
  wrapper.style.cssText =
    "position:fixed;left:-9999px;top:0;width:" +
    A4_W_PX +
    "px;min-height:" +
    A4_H_PX +
    "px;overflow:visible;";
  wrapper.innerHTML = buildReportHtml(data);
  document.body.appendChild(wrapper);

  const reportEl = wrapper.querySelector(".report") as HTMLElement;
  if (!reportEl) {
    document.body.removeChild(wrapper);
    return;
  }

  const doCapture = () =>
    html2canvas(reportEl, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff",
    width: A4_W_PX,
    height: reportEl.offsetHeight,
    windowWidth: A4_W_PX,
    windowHeight: reportEl.offsetHeight,
  });

  const run = () => {
    doCapture()
      .then((canvas) => {
      document.body.removeChild(wrapper);

      const imgW = canvas.width;
      const imgH = canvas.height;
      const a4W = 210;
      const a4H = 297;
      const pdf = new jsPDF({ unit: "mm", format: "a4" });

      if (imgH <= (imgW * a4H) / a4W) {
        const w = a4W;
        const h = (imgH * a4W) / imgW;
        pdf.addImage(canvas.toDataURL("image/jpeg", 0.92), "JPEG", 0, 0, w, h);
      } else {
        const singlePageH = (imgW * a4H) / a4W;
        let drawn = 0;
        while (drawn < imgH) {
          const srcH = Math.min(singlePageH, imgH - drawn);
          const srcY = drawn;
          const subCanvas = document.createElement("canvas");
          subCanvas.width = imgW;
          subCanvas.height = Math.min(singlePageH, imgH - drawn);
          const ctx = subCanvas.getContext("2d")!;
          ctx.fillStyle = "#ffffff";
          ctx.fillRect(0, 0, subCanvas.width, subCanvas.height);
          ctx.drawImage(canvas, 0, srcY, imgW, srcH, 0, 0, imgW, subCanvas.height);
          const hMm = (subCanvas.height * a4W) / imgW;
          pdf.addImage(subCanvas.toDataURL("image/jpeg", 0.92), "JPEG", 0, 0, a4W, hMm);
          drawn += srcH;
          if (drawn < imgH) pdf.addPage();
        }
      }

      pdf.save(`Jiayi-Risk-Compass-Report-${Date.now()}.pdf`);
      })
      .catch(() => {
        document.body.removeChild(wrapper);
      });
  };

  requestAnimationFrame(() => {
    requestAnimationFrame(run);
  });
}
